//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsUltraList.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lista()
        {
            this.Articulo = new HashSet<Articulo>();
        }
    
        public int id_lista { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> descripcion { get; set; }
        public Nullable<int> privacidad { get; set; }
        public Nullable<int> usuario_agrego { get; set; }
        public Nullable<System.DateTime> fecha_agrego { get; set; }
        public Nullable<int> usuario_modifico { get; set; }
        public Nullable<System.DateTime> fecha_modifico { get; set; }
        public Nullable<int> estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articulo> Articulo { get; set; }
    }
}
