//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsUltraList.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeGusta
    {
        public int id_me_gusta { get; set; }
        public Nullable<int> id_oferta { get; set; }
        public Nullable<int> id_usuario { get; set; }
    }
}
