//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsUltraList.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta
    {
        public int id_oferta { get; set; }
        public int id_articulo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string categoria { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> usuario_agrego { get; set; }
        public Nullable<System.DateTime> fecha_agrego { get; set; }
        public Nullable<int> usuario_modifico { get; set; }
        public Nullable<System.DateTime> fecha_modifico { get; set; }
        public Nullable<int> estatus { get; set; }
        public string image_path { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> lng { get; set; }
    }
}
